// Viaje de muestra (JSON del contrato) para probar la app sin datos propios.
// Provincia de Cádiz — el mismo ejemplo del contrato, ampliado para que las cinco
// vistas tengan algo que enseñar (lugares, bases, eventos, gastronomía, guía, itinerario).

export const EXAMPLE_TRIP = {
  version: 1,
  destino: 'Provincia de Cádiz',
  fechas: { inicio: '2026-08-01', fin: '2026-08-08' },
  bases: [
    {
      id: 'b1',
      nombre: 'Puerto Real',
      coords: [36.5297, -6.1897],
      activa: true,
      notas: 'Cercanías C-1 a Cádiz y Jerez. Bien situado para moverse por toda la bahía.',
    },
    {
      id: 'b2',
      nombre: 'Conil de la Frontera',
      coords: [36.2769, -6.0894],
      activa: false,
      notas: 'Más cerca de las playas del sur (Bolonia, Zahara), más lejos de Jerez.',
    },
  ],
  lugares: [
    {
      id: 'l1',
      nombre: 'Playa de Bolonia',
      categoria: 'playa',
      coords: [36.0894, -5.7742],
      municipio: 'Tarifa',
      imprescindible: true,
      duracion_estimada_min: 240,
      mejor_momento: 'Mañana. Evitar días de levante fuerte.',
      notas: 'Duna de 30 m. Aparcamiento gratuito pero se llena antes de las 11h.',
      fuente: 'investigacion',
    },
    {
      id: 'l2',
      nombre: 'Casco histórico de Cádiz',
      categoria: 'cultura',
      coords: [36.5297, -6.2926],
      municipio: 'Cádiz',
      imprescindible: true,
      duracion_estimada_min: 180,
      mejor_momento: 'Tarde, cuando baja el calor.',
      notas: 'Catedral, barrio de La Viña y Torre Tavira. Muy caminable.',
      fuente: 'investigacion',
    },
    {
      id: 'l3',
      nombre: 'Vejer de la Frontera',
      categoria: 'pueblo',
      coords: [36.2519, -5.9647],
      municipio: 'Vejer',
      imprescindible: false,
      duracion_estimada_min: 150,
      mejor_momento: 'Atardecer desde el mirador.',
      notas: 'Pueblo blanco en lo alto. Calles empinadas; aparcar abajo y subir.',
      fuente: 'investigacion',
    },
    {
      id: 'l4',
      nombre: 'Bodegas de Jerez (Tío Pepe)',
      categoria: 'actividad',
      coords: [36.6785, -6.1362],
      municipio: 'Jerez de la Frontera',
      imprescindible: false,
      duracion_estimada_min: 120,
      mejor_momento: 'Reserva con antelación para la visita guiada.',
      notas: 'Visita con cata. Hay tren turístico entre las naves.',
      fuente: 'investigacion',
    },
    {
      id: 'l5',
      nombre: 'Mirador de Vejer',
      categoria: 'mirador',
      coords: [36.2531, -5.9664],
      municipio: 'Vejer',
      imprescindible: false,
      duracion_estimada_min: 30,
      mejor_momento: 'Puesta de sol.',
      notas: 'Vistas a la campiña y, en días claros, a la costa.',
      fuente: 'investigacion',
    },
    {
      id: 'l6',
      nombre: 'Playa de Zahara de los Atunes',
      categoria: 'playa',
      coords: [36.1358, -5.8497],
      municipio: 'Zahara',
      imprescindible: false,
      duracion_estimada_min: 180,
      mejor_momento: 'Todo el día. Comer atún de almadraba en el pueblo.',
      notas: 'Arena fina y kilómetros de playa. Menos masificada que otras.',
      fuente: 'investigacion',
    },
  ],
  eventos: [
    {
      id: 'e1',
      nombre: 'Carreras de Caballos de Sanlúcar',
      fecha_inicio: '2026-08-08',
      fecha_fin: '2026-08-10',
      lugar_id: null,
      coords: [36.7891, -6.3547],
      notas: 'Llegar con mucha antelación. Aparcar lejos y caminar.',
    },
  ],
  gastronomia: [
    {
      id: 'g1',
      nombre: 'Freiduría La Marina',
      municipio: 'El Puerto de Santa María',
      coords: [36.5945, -6.2331],
      tipo: 'pescaíto',
      notas: 'Pescaíto frito para llevar en cucurucho. Clásico de la zona.',
    },
    {
      id: 'g2',
      nombre: 'Mercado Central de Abastos',
      municipio: 'Cádiz',
      coords: [36.5311, -6.2967],
      tipo: 'mercado',
      notas: 'Rincón gastronómico: pide en varios puestos y come de pie.',
    },
  ],
  logistica: {
    transporte: [
      'Coche imprescindible para el 90% del viaje.',
      'Cercanías C-1 conecta Cádiz, Puerto Real, El Puerto y Jerez sin aparcar.',
    ],
    apps: [
      { nombre: 'Windguru', para_que: 'Parte de viento (levante) antes de ir a la playa.' },
      { nombre: 'Renfe Cercanías', para_que: 'Horarios de la C-1.' },
    ],
    avisos: [
      'Carretera de la duna de Bolonia con tráfico denso los fines de semana de agosto.',
      'Con levante fuerte, algunas playas son incómodas: consulta el viento el día antes.',
    ],
  },
  secciones_guia: [
    {
      id: 's1',
      titulo: 'Cuándo ir y qué esperar',
      contenido_md: '## Agosto en Cádiz\n\nCalor seco y **levante**: el viento de poniente/levante manda sobre los planes de playa. Con levante fuerte, la arena vuela y el baño es incómodo en la costa atlántica.\n\n- Consulta el viento la noche antes.\n- Reserva alojamiento y bodegas con antelación: es temporada alta.',
      lugares_relacionados: ['l1', 'l6'],
    },
    {
      id: 's2',
      titulo: 'Los pueblos blancos',
      contenido_md: '## Pueblos blancos\n\nVejer es el más espectacular de la zona sur: casco amurallado en lo alto, calles empinadas y miradores con vistas a la campiña.\n\n> Consejo: aparca en la parte baja y sube andando; arriba casi no hay sitio.',
      lugares_relacionados: ['l3', 'l5'],
    },
  ],
  itinerarios: [
    {
      dia: 1,
      fecha: '2026-08-01',
      base_id: 'b1',
      paradas: ['l2', 'l4'],
      notas: 'Día de ciudad: Cádiz por la tarde y bodegas en Jerez.',
    },
    {
      dia: 2,
      fecha: '2026-08-02',
      base_id: 'b1',
      paradas: ['l1', 'l3', 'l5'],
      notas: 'Playa de Bolonia por la mañana y Vejer al atardecer.',
    },
  ],
};
